---
- name: register pi model
  when: sbc_model is not defined
  block:
    - name: create facts directory
      ansible.builtin.file:
        path: '/etc/ansible/facts.d'
        state: directory
        recurse: true

    - name: set sbc_model fact file
      ansible.builtin.copy:
        src: sbc_model.fact
        dest: /etc/ansible/facts.d/sbc_model.fact

    - name: call setup again
      ansible.builtin.setup:

- name: set default values
  ansible.builtin.include_vars:
    file: rpi_4b.yml

- name: raspberry pi 4b
  when: sbc_model.startswith("Raspberry Pi 4 Model B")
  ansible.builtin.include_vars:
    file: rpi_4b.yml

- name: raspberry pi zero w
  when: sbc_model.startswith("Raspberry Pi Zero W")
  ansible.builtin.include_vars:
    file: rpi_zero_w.yml

- ansible.builtin.include_tasks: raspi-config.yml
- ansible.builtin.include_tasks: uv4l.yml
