---
# assumes raspberry pi 4b with 4GB of ram
# TODO: smarter gpu memory limits. must have at least 256MB for gpu
- name: configure gpu memory
  ansible.builtin.shell:
    cmd: raspi-config nonint do_memory_split {{ rpi_gpu_mem_mb }}

- name: raspberry pi update
  ansible.builtin.shell:
    cmd: rpi-update
  environment:
    SKIP_WARNING: "1"
  notify:
    - Reboot

- name: write udev rule for picam
  ansible.builtin.copy:
    dest: /etc/udev/rules.d/99-camera.rules
    content: 'SUBSYSTEM=="vchiq",MODE="0666"'
  notify:
    - Reload udev

- name: ensure picamera2 is installed
  ansible.builtin.apt:
    name: python3-picamera2
    install_recommends: false
    state: latest
    update_cache: true
