---
# assumes raspberry pi 4b with 4GB of ram
# TODO: smarter gpu memory limits. must have at least 256MB for gpu
- name: configure gpu memory
  ansible.builtin.shell:
    cmd: raspi-config nonint do_memory_split {{ rpi_gpu_mem_mb }}

- name: enable camera
  ansible.builtin.shell:
    cmd: raspi-config nonint do_camera 0

- name: raspberry pi update
  ansible.builtin.shell:
    cmd: rpi-update
  environment:
    SKIP_WARNING: "1"
  notify:
    - Reboot