---
- name: Add uv4l repo key
  ansible.builtin.apt_key:
    url: https://www.linux-projects.org/listing/uv4l_repo/lpkey.asc
    state: present

- name: configure uv4l repo
  ansible.builtin.apt_repository:
    state: present
    filename: uv4l
    repo: "deb https://www.linux-projects.org/listing/uv4l_repo/raspbian/stretch stretch main"

- name: install uv4l
  ansible.builtin.apt:
    state: present
    name:
      - uv4l
      - uv4l-raspicam
      - uv4l-raspicam-extras
      - uv4l-server
      - uv4l-uvc
      - uv4l-xscreen
      - uv4l-mjpegstream
      - uv4l-dummy
      - uv4l-raspidisp
      - "{{ uv4l_webrtc_package }}"

- name: configure uv4l
  ansible.builtin.copy:
    src: raspicam.conf
    dest: /etc/uv4l/uv4l-raspicam.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart uv4l

- name: enable uv4l at boot
  ansible.builtin.service:
    name: uv4l_raspicam
    enabled: true
